# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - local
    ports:
      - "5436:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  gateway:
    image: ghcr.io/novikoff-vvs/telegram-bots-gateway:master
    pull_policy: always
    container_name: gateway
    volumes:
      - .env:/app/.env
    depends_on:
      - db
    networks:
      - local

  files_bot:
    container_name: files_bot
    pull_policy: always
    image: ghcr.io/novikoff-vvs/files-bot:main
    volumes:
      - ./services/files-bot/.env:/app/.env
    networks:
      - local
    depends_on:
      - gateway
    expose:
      - "50053"


networks:
  local:

volumes:
  pgdata:   # Docker-managed volume
    driver: local  # Используем стандартный локальный драйвер