# Use postgres/example user/password credentials
version: '3.9'

services:
  db:
    image: postgres
    container_name: db
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5436:5432
    networks:
      - local
    volumes:
      - pgdata:/var/lib/postgresql/data


  gateway:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: gateway
    volumes:
      - .env:/app/.env
    depends_on:
      - db
    networks:
      - local

  files_bot:
    container_name: files_bot
    build:
      dockerfile: .docker/Dockerfile
      context: ./services/files-bot-service/
    volumes:
      - ./services/files-bot-service/.env:/app/.env
    networks:
      - local
    depends_on:
      - gateway
    expose:
      - "50053"


networks:
  local:

volumes:
  pgdata:   # Docker-managed volume
    driver: local  # Используем стандартный локальный драйвер