// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.28.1
// source: services/queuingbot/queueingbot.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueuingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint64                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,5,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuingMessage) Reset() {
	*x = QueuingMessage{}
	mi := &file_services_queuingbot_queueingbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuingMessage) ProtoMessage() {}

func (x *QueuingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_services_queuingbot_queueingbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuingMessage.ProtoReflect.Descriptor instead.
func (*QueuingMessage) Descriptor() ([]byte, []int) {
	return file_services_queuingbot_queueingbot_proto_rawDescGZIP(), []int{0}
}

func (x *QueuingMessage) GetMessageId() uint64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *QueuingMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type QueuingBoolResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueuingBoolResult) Reset() {
	*x = QueuingBoolResult{}
	mi := &file_services_queuingbot_queueingbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueuingBoolResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueuingBoolResult) ProtoMessage() {}

func (x *QueuingBoolResult) ProtoReflect() protoreflect.Message {
	mi := &file_services_queuingbot_queueingbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueuingBoolResult.ProtoReflect.Descriptor instead.
func (*QueuingBoolResult) Descriptor() ([]byte, []int) {
	return file_services_queuingbot_queueingbot_proto_rawDescGZIP(), []int{1}
}

func (x *QueuingBoolResult) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

var File_services_queuingbot_queueingbot_proto protoreflect.FileDescriptor

var file_services_queuingbot_queueingbot_proto_rawDesc = string([]byte{
	0x0a, 0x25, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x69,
	0x6e, 0x67, 0x62, 0x6f, 0x74, 0x2f, 0x71, 0x75, 0x65, 0x75, 0x65, 0x69, 0x6e, 0x67, 0x62, 0x6f,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x69, 0x6e,
	0x67, 0x42, 0x6f, 0x74, 0x22, 0x43, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x09, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0x2b, 0x0a, 0x11, 0x51, 0x75, 0x65,
	0x75, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x56, 0x0a, 0x0b, 0x51, 0x75, 0x65, 0x75, 0x65, 0x69,
	0x6e, 0x67, 0x42, 0x6f, 0x74, 0x12, 0x47, 0x0a, 0x06, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x12,
	0x1b, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x74, 0x2e, 0x51, 0x75,
	0x65, 0x75, 0x69, 0x6e, 0x67, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1e, 0x2e, 0x51,
	0x75, 0x65, 0x75, 0x65, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x74, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x69,
	0x6e, 0x67, 0x42, 0x6f, 0x6f, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x41,
	0x0a, 0x1c, 0x69, 0x6f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x73, 0x2e, 0x51, 0x75, 0x65, 0x75, 0x65, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x74, 0x42, 0x10,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x69, 0x6e, 0x67, 0x42, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_services_queuingbot_queueingbot_proto_rawDescOnce sync.Once
	file_services_queuingbot_queueingbot_proto_rawDescData []byte
)

func file_services_queuingbot_queueingbot_proto_rawDescGZIP() []byte {
	file_services_queuingbot_queueingbot_proto_rawDescOnce.Do(func() {
		file_services_queuingbot_queueingbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_queuingbot_queueingbot_proto_rawDesc), len(file_services_queuingbot_queueingbot_proto_rawDesc)))
	})
	return file_services_queuingbot_queueingbot_proto_rawDescData
}

var file_services_queuingbot_queueingbot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_services_queuingbot_queueingbot_proto_goTypes = []any{
	(*QueuingMessage)(nil),    // 0: QueueingBot.QueuingMessage
	(*QueuingBoolResult)(nil), // 1: QueueingBot.QueuingBoolResult
}
var file_services_queuingbot_queueingbot_proto_depIdxs = []int32{
	0, // 0: QueueingBot.QueueingBot.Handle:input_type -> QueueingBot.QueuingMessage
	1, // 1: QueueingBot.QueueingBot.Handle:output_type -> QueueingBot.QueuingBoolResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_services_queuingbot_queueingbot_proto_init() }
func file_services_queuingbot_queueingbot_proto_init() {
	if File_services_queuingbot_queueingbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_queuingbot_queueingbot_proto_rawDesc), len(file_services_queuingbot_queueingbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_queuingbot_queueingbot_proto_goTypes,
		DependencyIndexes: file_services_queuingbot_queueingbot_proto_depIdxs,
		MessageInfos:      file_services_queuingbot_queueingbot_proto_msgTypes,
	}.Build()
	File_services_queuingbot_queueingbot_proto = out.File
	file_services_queuingbot_queueingbot_proto_goTypes = nil
	file_services_queuingbot_queueingbot_proto_depIdxs = nil
}
