// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: proto/files-bot-service.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilesBot_Handle_FullMethodName = "/FilesBot.FilesBot/Handle"
)

// FilesBotClient is the client API for FilesBot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FilesBotClient interface {
	Handle(ctx context.Context, in *FilesBotMessage, opts ...grpc.CallOption) (*FilesBotResult, error)
}

type filesBotClient struct {
	cc grpc.ClientConnInterface
}

func NewFilesBotClient(cc grpc.ClientConnInterface) FilesBotClient {
	return &filesBotClient{cc}
}

func (c *filesBotClient) Handle(ctx context.Context, in *FilesBotMessage, opts ...grpc.CallOption) (*FilesBotResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilesBotResult)
	err := c.cc.Invoke(ctx, FilesBot_Handle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilesBotServer is the server API for FilesBot service.
// All implementations must embed UnimplementedFilesBotServer
// for forward compatibility.
type FilesBotServer interface {
	Handle(context.Context, *FilesBotMessage) (*FilesBotResult, error)
	mustEmbedUnimplementedFilesBotServer()
}

// UnimplementedFilesBotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilesBotServer struct{}

func (UnimplementedFilesBotServer) Handle(context.Context, *FilesBotMessage) (*FilesBotResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedFilesBotServer) mustEmbedUnimplementedFilesBotServer() {}
func (UnimplementedFilesBotServer) testEmbeddedByValue()                  {}

// UnsafeFilesBotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilesBotServer will
// result in compilation errors.
type UnsafeFilesBotServer interface {
	mustEmbedUnimplementedFilesBotServer()
}

func RegisterFilesBotServer(s grpc.ServiceRegistrar, srv FilesBotServer) {
	// If the following call pancis, it indicates UnimplementedFilesBotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilesBot_ServiceDesc, srv)
}

func _FilesBot_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FilesBotMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilesBotServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilesBot_Handle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilesBotServer).Handle(ctx, req.(*FilesBotMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// FilesBot_ServiceDesc is the grpc.ServiceDesc for FilesBot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilesBot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FilesBot.FilesBot",
	HandlerType: (*FilesBotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _FilesBot_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/files-bot-service.proto",
}
